services:
  app:
    container_name: jenkins_app
    build:
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - .data/jenkins_home:/var/jenkins_home
      - .data/docker-certs-client:/certs/client:ro
    environment:
      JAVA_OPTS: "-Dhudson.model.DirectoryBrowserSupport.CSP=\"default-src 'self'; style-src-elem *; font-src *; img-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-hashes'; style-src 'self' 'unsafe-inline' data:\""
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
  docker:
    container_name: jenkins_dind
    image: docker:dind
    privileged: true
    restart: always
    volumes:
      - .data/jenkins_home:/var/jenkins_home
      - .data/docker-certs-ca:/certs/ca
      - .data/docker-certs-client:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: /certs
