services:
  app:
    container_name: jenkins_app
    build:
      context: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - .data/jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: >-
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Vancouver
        -Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self'; style-src-elem *; font-src *; img-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-hashes'; style-src 'self' 'unsafe-inline' data:"
      DOCKER_HOST: socat:2375
    depends_on:
      - socat

  # fixes /var/run/docker.sock binding in mac (docker desktop always sets socket to root:root so jenkins user cannot run it directly even with docker group)
  socat:
    container_name: jenkins_socat
    image: alpine/socat
    command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
    user: root
    volumes:
      - /var/run/docker.sock.raw:/var/run/docker.sock

  mail:
    container_name: jenkins_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"